### ISSUE TITLE
/src/style/widget/weui-tips/weui-loadmore.less 缺少部分样式

### ISSUE THREAD

**Issue by cfanbo** [wepyjs/wepy-weui-demo#20]
和官方的相比，缺少以下样式
.weui-loadmore_dot{
    .weui-loadmore__tips{
        padding:0 .16em;
        &:before{
            content: " ";
            width:4px;
            height:4px;
            border-radius:50%;
            background-color: @weuiLineColorLight;
            display: inline-block;
            position: relative;
            vertical-align: 0;
            top:-.16em;
        }
    }    
}
.weui-loadmore__tips_in-dot{
    position: relative;
    padding:0 .16em;
    width: 4px;
    height: 1.6em;
    &:before{
        content: " ";
        position: absolute;
        top: 50%;
        left: 50%;
        margin-top: -1px;
        margin-left: -2px;
        width: 4px;
        height: 4px;
        border-radius: 50%;
        background-color: @weuiLineColorLight;
    }
}

**Comment by Gcaufy** [comment]
可能是因为代码更新导致的吧，欢迎pr进来。
